import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { mount } from '@vue/test-utils'
import i18n from '@/i18n/index.js'
import AuditView from '@/views/AuditView.vue'

const fixedNow = new Date('2026-04-02T10:15:00.000Z')

const mocks = vi.hoisted(() => ({
  route: { query: {} },
  getAudit: vi.fn(),
  getChainOfCustody: vi.fn(),
  confirmChainOfCustodyHandoff: vi.fn(),
  getDrives: vi.fn(),
  canAccess: vi.fn(),
  authStore: { username: 'auditor-user' },
  settingsStore: { downloadRevokeDelayMs: 0, auditExportFilename: 'audit-log' },
}))

vi.mock('vue-router', () => ({
  useRoute: () => mocks.route,
}))

vi.mock('@/api/audit.js', () => ({
  getAudit: (...args) => mocks.getAudit(...args),
  getChainOfCustody: (...args) => mocks.getChainOfCustody(...args),
  confirmChainOfCustodyHandoff: (...args) => mocks.confirmChainOfCustodyHandoff(...args),
}))

vi.mock('@/api/drives.js', () => ({
  getDrives: (...args) => mocks.getDrives(...args),
}))

vi.mock('@/composables/useRoleGuard.js', () => ({
  useRoleGuard: () => ({ canAccess: mocks.canAccess }),
}))

vi.mock('@/stores/auth.js', () => ({
  useAuthStore: () => mocks.authStore,
}))

vi.mock('@/stores/settings.js', () => ({
  useSettingsStore: () => mocks.settingsStore,
}))

async function flushPromises() {
  await Promise.resolve()
  await Promise.resolve()
  await Promise.resolve()
}

function mountView() {
  return mount(AuditView, {
    global: {
      plugins: [i18n],
      stubs: {
        DataTable: { template: '<div class="data-table-shell"><slot /></div>' },
        Pagination: { template: '<div class="pagination" />' },
        ConfirmDialog: { template: '<div />' },
      },
    },
  })
}

describe('AuditView chain of custody report', () => {
  beforeEach(() => {
    vi.useFakeTimers()
    vi.setSystemTime(fixedNow)
    mocks.route.query = {}
    mocks.getAudit.mockReset()
    mocks.getChainOfCustody.mockReset()
    mocks.confirmChainOfCustodyHandoff.mockReset()
    mocks.getDrives.mockReset()
    mocks.canAccess.mockReset()

    mocks.getAudit.mockResolvedValue([])
    mocks.getDrives.mockResolvedValue([
      {
        id: 1,
        device_identifier: 'sdb',
        display_device_label: 'Kingston DataTraveler - Port 1',
        current_state: 'IN_USE',
        current_project_id: 'PRJ-001',
      },
    ])
    mocks.canAccess.mockReturnValue(true)
    mocks.getChainOfCustody.mockResolvedValue({
      selector_mode: 'PROJECT',
      project_id: 'PRJ-001',
      reports: [
        {
          drive_id: 1,
          drive_sn: 'SN-001',
          project_id: 'PRJ-001',
          delivery_time: '2026-04-01T14:30:00.000Z',
          custody_complete: true,
          manifest_summary: [
            {
              job_id: 12,
              total_files: 3,
              total_bytes: 1024,
              manifest_count: 1,
              latest_manifest_path: '/reports/manifests/12.json',
              latest_manifest_format: 'json',
              latest_manifest_created_at: '2026-04-01T14:00:00.000Z',
            },
          ],
          chain_of_custody_events: [
            {
              event_id: 1,
              event_type: 'DRIVE_INITIALIZED',
              timestamp: '2026-04-01T13:00:00.000Z',
              actor: 'auditor-user',
              action: 'Drive initialized',
              details: { drive_id: 1, project_id: 'PRJ-001' },
            },
          ],
        },
      ],
    })
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('renders the structured CoC report after loading data', async () => {
    const wrapper = mountView()
    await flushPromises()

    await wrapper.find('select').setValue('1')
    await wrapper.findAll('button').find((node) => node.text() === i18n.global.t('audit.loadCoc')).trigger('click')
    await flushPromises()

    expect(wrapper.text()).toContain('Report Header')
    expect(wrapper.text()).toContain('Generated By')
    expect(wrapper.text()).toContain('auditor-user')
    expect(wrapper.text()).toContain('Events Timeline')
    expect(wrapper.text()).toContain('Drive initialized')
    expect(wrapper.text()).toContain('/reports/manifests/12.json')
    expect(wrapper.text()).toContain('Attestation')
  })

  it('exports CoC CSV rows from the currently loaded report', async () => {
    const createObjectURLSpy = vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:coc')
    const revokeObjectURLSpy = vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => {})
    const clickSpy = vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})

    const wrapper = mountView()
    await flushPromises()

    await wrapper.find('select').setValue('1')
    await wrapper.findAll('button').find((node) => node.text() === i18n.global.t('audit.loadCoc')).trigger('click')
    await flushPromises()

    await wrapper.findAll('button').find((node) => node.text() === i18n.global.t('audit.exportCsv')).trigger('click')

    expect(createObjectURLSpy).toHaveBeenCalledTimes(1)

    clickSpy.mockRestore()
    createObjectURLSpy.mockRestore()
    revokeObjectURLSpy.mockRestore()
  })

  it('restores the previous generation timestamp when an archived drive returns 410', async () => {
    const originalGeneratedAt = '2026-04-02 10:15:00 UTC'

    const wrapper = mountView()
    await flushPromises()

    await wrapper.find('select').setValue('1')
    await wrapper.findAll('button').find((node) => node.text() === i18n.global.t('audit.loadCoc')).trigger('click')
    await flushPromises()

    expect(wrapper.html()).toContain(originalGeneratedAt)

    vi.setSystemTime(new Date('2026-04-03T12:00:00.000Z'))
    mocks.getChainOfCustody.mockRejectedValueOnce({ response: { status: 410 } })

    await wrapper.findAll('button').find((node) => node.text() === i18n.global.t('audit.loadCoc')).trigger('click')
    await flushPromises()

    expect(wrapper.text()).toContain('Drive initialized')
    expect(wrapper.html()).toContain(originalGeneratedAt)
    expect(wrapper.html()).not.toContain('2026-04-03 12:00:00 UTC')
  })
})