import { describe, expect, it } from 'vitest'
import { mount } from '@vue/test-utils'
import i18n from '@/i18n/index.js'
import CocReport from '@/components/audit/CocReport.vue'

function mountView(props = {}) {
  return mount(CocReport, {
    props: {
      report: {
        drive_id: 7,
        drive_sn: 'SN-777',
        drive_manufacturer: 'SanDisk',
        drive_model: 'Extreme Pro',
        project_id: 'PRJ-777',
        custody_complete: true,
        delivery_time: '2026-04-28T14:15:16Z',
        chain_of_custody_events: [
          {
            event_id: 11,
            event_type: 'DRIVE_INITIALIZED',
            timestamp: '2026-04-28T13:00:00Z',
            actor: 'auditor-user',
            action: 'Drive initialized',
            details: { drive_id: 7, project_id: 'PRJ-777' },
          },
          {
            event_id: 12,
            event_type: 'COC_HANDOFF_CONFIRMED',
            timestamp: '2026-04-28T14:15:16Z',
            actor: 'manager-user',
            action: 'Custody handoff confirmed',
            details: {
              possessor: 'Officer Jane Doe',
              received_by: 'Archive Clerk',
              receipt_ref: 'REC-42',
              notes: 'Sealed container intact',
            },
          },
        ],
        manifest_summary: [
          {
            job_id: 99,
            total_files: 12,
            total_bytes: 4096,
            manifest_count: 2,
            latest_manifest_path: '/reports/manifests/99.json',
            latest_manifest_format: 'json',
            latest_manifest_created_at: '2026-04-28T14:00:00Z',
          },
        ],
      },
      selectorMode: 'PROJECT',
      projectId: 'PRJ-777',
      generatedAt: '2026-04-28T15:00:00Z',
      generatedBy: 'auditor-user',
      manifestTotalsFootnote: 'Manifest totals reflect files and bytes recorded for this drive assignment.',
      ...props,
    },
    global: {
      plugins: [i18n],
    },
  })
}

describe('CocReport', () => {
  it('renders a structured report with UTC timestamps and manifest fields', () => {
    const wrapper = mountView()

    expect(wrapper.text()).toContain('Report Header')
    expect(wrapper.text()).toContain('Generated By')
    expect(wrapper.text()).toContain('auditor-user')
    expect(wrapper.text()).toContain('2026-04-28 15:00:00 UTC')
    expect(wrapper.text()).toContain('Drive Identity')
    expect(wrapper.text()).toContain('Manufacturer')
    expect(wrapper.text()).toContain('SanDisk')
    expect(wrapper.text()).toContain('Model')
    expect(wrapper.text()).toContain('Extreme Pro')
    expect(wrapper.text()).toContain('Custody Status')
    expect(wrapper.text()).toContain('Officer Jane Doe')
    expect(wrapper.text()).toContain('Archive Clerk')
    expect(wrapper.text()).toContain('REC-42')
    expect(wrapper.text()).toContain('Sealed container intact')
    expect(wrapper.text()).toContain('Events Timeline')
    expect(wrapper.text()).toContain('Drive initialized')
    expect(wrapper.text()).not.toContain('DRIVE_INITIALIZED')
    expect(wrapper.text()).toContain('/reports/manifests/99.json')
    expect(wrapper.text()).toContain('json')
    expect(wrapper.text()).toContain('2026-04-28 14:00:00 UTC')
    expect(wrapper.text()).toContain('Printed by:')
    expect(wrapper.text()).toContain('Date:')
  })

  it('renders placeholders when optional handoff and manifest fields are missing', () => {
    const wrapper = mountView({
      report: {
        drive_id: 8,
        drive_sn: 'SN-888',
        drive_manufacturer: null,
        drive_model: null,
        project_id: null,
        custody_complete: false,
        delivery_time: null,
        chain_of_custody_events: [],
        manifest_summary: [],
      },
    })

    expect(wrapper.text()).toContain('No events recorded')
    expect(wrapper.text()).toContain('No manifest summary available')
    expect(wrapper.text()).toContain('Delivery Time (UTC)')
    expect(wrapper.text()).toContain('-')
  })
})